#%RAML 1.0
---
title: maestro-workflow-manager
version: v1
baseUri: /{version}/maestro

mediaType: application/json

/templates:
  post:
    description: Creates a new workflow template
    body:
      schema: !include schemas/createTemplate.json
      example: !include examples/createTemplate.json
    responses: !include responses/createTemplate.yml
  get:
    description: Retrieves all the registered templates
    responses: !include responses/getTemplates.yml
  /{templatedId}:
    uriParameters:
      templatedId:
        displayName: Name of the template
        type: string
        required: true
    get:
      description: Retrieves a registered template
      responses: !include responses/getTemplate.yml
    delete:
      description: Deletes a template
      responses: !include responses/deleteTemplate.yml
    patch:
      description: Updates an existing workflow template
      body:
        schema: !include schemas/createTemplate.json
        example: !include examples/createTemplate.json
      responses: !include responses/updateTemplate.yml

/executeFlow/{flowId}:
  uriParameters:
    flowId:
      displayName: The name of the flow to execute
      type: string
      required: true
  post:
    description: Executes a workflow template
    body:
      schema: !include schemas/executeWorkflow.json
      example: !include examples/executeWorkflow.json
    responses: !include responses/executeWorkflow.yml

/resumeFlow:
  post:
    description: Resumes an errored workflow
    body:
      schema: !include schemas/resumeWorkflow.json
      example: !include examples/resumeWorkflow.json
    responses: !include responses/resumeWorkflow.yml

/flows:
  get:
    description: Retrieves all the started and executed flows
    queryParameters:
      from:
        description: Specifies since which date we would like to retrieve workflows
        type: date
        required: false
        example: 2018-01-02
      to:
        description: Specifies until which date we would like to retrieve workflows
        type: date
        required: false
        example: 2018-05-02
      processName:
        description: Specifies which type of process we would like to retrieve workflows for
        type: string
        required: false
        example: test-1
      processUuid:
        description: Specifies which exact process we would like to retrieve workflows for
        type: string
        required: false
        example: ﻿2ee38689-676c-4820-8a0c-c92298520ccf
      status:
        description: A comma separated list of the process final status we would like to retrieve
        type: string
        required: false
        example: ﻿COMPLETED,FAILED,RESTARTED
    responses: !include responses/retrieveWorkflows.yml
